/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_xm_util_GetIpPort */

#ifndef _Included_com_example_xm_util_GetIpPort
#define _Included_com_example_xm_util_GetIpPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_xm_util_GetIpPort
 * Method:    getIpString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_xm_util_GetIpPort_getIpString
  (JNIEnv *, jobject);

/*
 * Class:     com_example_xm_util_GetIpPort
 * Method:    getPortString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_xm_util_GetIpPort_getPortString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
