/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_xm_util_GetIpPort */

#ifndef _Included_com_example_xm_util_GetIpPort
#define _Included_com_example_xm_util_GetIpPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_xm_util_GetIpPort
 * Method:    getIpString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_xm_util_GetIpPort_getIpString
        (JNIEnv * env, jobject jObj){
  return (*env)->NewStringUTF(env,"115.159.185.15");
//  return (*env)->NewStringUTF(env,"192.168.153.1");
}

/*
 * Class:     com_example_xm_util_GetIpPort
 * Method:    getPortString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_xm_util_GetIpPort_getPortString
  (JNIEnv * env, jobject obj){
//  return (*env)->NewStringUTF(env,"9998");
  return (*env)->NewStringUTF(env,"9929");
  }

#ifdef __cplusplus
}
#endif
#endif
